
const {
  Document, Packer, Paragraph, TextRun,
  AlignmentType, BorderStyle, LevelFormat
} = require('docx');
const fs = require('fs');

const dataPath   = process.argv[2];
const outputPath = process.argv[3];
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const BULLETS = {
  numbering: { config: [{ reference: "bullets", levels: [{
    level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
    style: { paragraph: { indent: { left: 360, hanging: 360 } } }
  }]}]}
};

function hr(color) {
  return new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: color || "2E75B6", space: 1 } },
    spacing: { after: 100 }
  });
}
function section(text, color) {
  return new Paragraph({
    children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 22, color: color || "2E75B6", font: "Arial" })],
    spacing: { before: 200, after: 80 }
  });
}
function body(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 20, font: "Arial" })],
    spacing: { after: 60 }
  });
}
function bullet(text) {
  return new Paragraph({
    numbering: { reference: "bullets", level: 0 },
    children: [new TextRun({ text, size: 20, font: "Arial" })],
    spacing: { after: 50 }
  });
}
function boldVal(label, val) {
  return new Paragraph({
    children: [
      new TextRun({ text: label + ": ", bold: true, size: 20, font: "Arial" }),
      new TextRun({ text: val, size: 20, font: "Arial" })
    ],
    spacing: { after: 60 }
  });
}

const color = data.color || "2E75B6";
const children = [];

// Name
children.push(new Paragraph({
  alignment: AlignmentType.CENTER, spacing: { after: 50 },
  children: [new TextRun({ text: data.name.toUpperCase(), bold: true, size: 44, font: "Arial", color })]
}));

// Contact
const contact = [data.email, data.phone, data.linkedin, data.github].filter(Boolean).join("  |  ");
children.push(new Paragraph({
  alignment: AlignmentType.CENTER, spacing: { after: 40 },
  children: [new TextRun({ text: contact, size: 18, font: "Arial", color: "555555" })]
}));

// Role line
children.push(new Paragraph({
  alignment: AlignmentType.CENTER, spacing: { after: 60 },
  children: [new TextRun({ text: data.occupation + "  |  " + data.department, size: 20, font: "Arial", color: "777777", italics: true })]
}));

children.push(hr(color));

// Summary
if (data.summary) {
  children.push(section("Professional Summary", color));
  children.push(body(data.summary));
  children.push(hr(color));
}

// Education
if (data.education && data.education.length > 0) {
  children.push(section("Education", color));
  for (const e of data.education) {
    if (e.degree) {
      children.push(new Paragraph({
        children: [new TextRun({ text: e.degree, bold: true, size: 22, font: "Arial" })],
        spacing: { after: 40 }
      }));
      const line = [e.college, e.year, e.grade].filter(Boolean).join("  |  ");
      if (line) children.push(body(line));
    }
  }
  children.push(hr(color));
}

// Skills
if (data.skills) {
  children.push(section("Technical Skills", color));
  children.push(boldVal("Technical", data.skills));
  if (data.softskills) children.push(boldVal("Soft Skills", data.softskills));
  children.push(hr(color));
}

// Experience
if (data.experience) {
  children.push(section("Experience", color));
  children.push(body(data.experience));
  children.push(hr(color));
}

// Projects
if (data.projects && data.projects.length > 0) {
  children.push(section("Projects", color));
  for (const p of data.projects) {
    if (p.name) {
      children.push(new Paragraph({
        children: [new TextRun({ text: p.name, bold: true, size: 22, font: "Arial" })],
        spacing: { after: 40 }
      }));
      if (p.description) {
        const lines = p.description.split('\n').filter(l => l.trim());
        for (const l of lines) children.push(bullet(l.trim()));
      }
      if (p.tech) children.push(boldVal("Tech Stack", p.tech));
      children.push(new Paragraph({ spacing: { after: 100 } }));
    }
  }
  children.push(hr(color));
}

// Certifications
if (data.certifications) {
  children.push(section("Certifications & Achievements", color));
  const certs = data.certifications.split('\n').filter(l => l.trim());
  for (const c of certs) children.push(bullet(c.trim()));
  children.push(hr(color));
}

// Footer
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Generated by AI Resume Analyzer", size: 16, font: "Arial", color: "aaaaaa", italics: true })]
}));

const doc = new Document({
  ...BULLETS,
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 } } },
    children
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync(outputPath, buf);
  console.log("done");
});
